# Azure DevOps Pipeline Script

trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Build'

- script: |
    docker build -t my-react-app:latest .
  displayName: 'Create Image'

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    command: 'login'
  displayName: 'Docker Login'
  env:
    DOCKER_USERNAME: $(DOCKER_USERNAME)
    DOCKER_PASSWORD: $(DOCKER_PASSWORD)

- script: |
    docker tag my-react-app:latest mahec/my-react-app:latest
    docker push mahec/my-react-app:latest
  displayName: 'Push to DockerHub'